#!/usr/bin/env node
// Fetches Wikipedia infobox thumbnails for each candidate in ../candidates.js,
// saves them to ../pics/<id>.<ext>, and writes ../pics/manifest.js
// mapping id -> relative path. Re-runnable; skips ids already present unless --force.

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PICS = path.join(ROOT, 'pics');
const MANIFEST = path.join(PICS, 'manifest.js');
const CANDIDATES_JS = path.join(ROOT, 'candidates.js');

const FORCE = process.argv.includes('--force');

function loadCandidates() {
  // Evaluate candidates.js inside a fake window so we can read CANDIDATES.
  const src = fs.readFileSync(CANDIDATES_JS, 'utf8');
  const sandbox = { window: {} };
  // eslint-disable-next-line no-new-func
  new Function('window', src)(sandbox.window);
  const main = sandbox.window.CANDIDATES || [];
  const ext = sandbox.window.EXTENDED_CANDIDATES || [];
  if (!main.length && !ext.length) {
    throw new Error('candidates.js did not set window.CANDIDATES or EXTENDED_CANDIDATES');
  }
  return [...main, ...ext];
}

function wikiTitleFromUrl(url) {
  if (!url) return null;
  const m = url.match(/wikipedia\.org\/wiki\/(.+)$/);
  return m ? decodeURIComponent(m[1]) : null;
}

async function fetchSummary(title) {
  const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`;
  const res = await fetch(url, {
    headers: { 'User-Agent': 'ranked_choice/0.1 (https://github.com/hsalberti/ranked_choice)' },
  });
  if (!res.ok) throw new Error(`summary ${res.status} for ${title}`);
  return res.json();
}

async function download(url, destNoExt) {
  let res, attempt = 0;
  while (true) {
    res = await fetch(url, {
      headers: { 'User-Agent': 'ranked_choice/0.1 (https://github.com/hsalberti/ranked_choice)' },
    });
    if (res.status !== 429 || attempt >= 5) break;
    const wait = 2000 * Math.pow(2, attempt);
    console.log(`  429 — backing off ${wait}ms`);
    await new Promise(r => setTimeout(r, wait));
    attempt++;
  }
  if (!res.ok) throw new Error(`download ${res.status}`);
  const ct = res.headers.get('content-type') || '';
  let ext = 'jpg';
  if (ct.includes('png')) ext = 'png';
  else if (ct.includes('webp')) ext = 'webp';
  else if (ct.includes('svg')) ext = 'svg';
  const buf = Buffer.from(await res.arrayBuffer());
  const dest = `${destNoExt}.${ext}`;
  fs.writeFileSync(dest, buf);
  return path.basename(dest);
}

function existingPhoto(id) {
  if (!fs.existsSync(PICS)) return null;
  const found = fs.readdirSync(PICS).find(f => /^([^.]+)\.(jpe?g|png|webp|svg)$/i.test(f) && f.split('.')[0] === id);
  return found || null;
}

function writeManifest(map) {
  const lines = [
    '// Auto-generated by scripts/fetch_portraits.js — do not edit by hand.',
    'window.CANDIDATE_PHOTOS = {',
    ...Object.keys(map).sort().map(id => `  ${JSON.stringify(id)}: ${JSON.stringify('pics/' + map[id])},`),
    '};',
    '',
  ];
  fs.writeFileSync(MANIFEST, lines.join('\n'));
}

async function main() {
  if (!fs.existsSync(PICS)) fs.mkdirSync(PICS, { recursive: true });
  const candidates = loadCandidates();
  console.log(`Loaded ${candidates.length} candidates`);

  const manifest = {};
  const misses = [];

  for (const c of candidates) {
    const existing = !FORCE && existingPhoto(c.id);
    if (existing) {
      manifest[c.id] = existing;
      console.log(`✓ ${c.id} (cached: ${existing})`);
      continue;
    }
    const title = wikiTitleFromUrl(c.links && c.links.wikipedia);
    if (!title) {
      misses.push({ id: c.id, reason: 'no wikipedia url' });
      continue;
    }
    try {
      const summary = await fetchSummary(title);
      // Use the thumbnail URL as-provided (~320px wide). Wikimedia restricts
      // arbitrary thumb sizes, so we don't try to upscale — 320px is plenty
      // for circular avatars and keeps the page weight low.
      const img = (summary.thumbnail && summary.thumbnail.source) ||
                  (summary.originalimage && summary.originalimage.source);
      if (!img) {
        misses.push({ id: c.id, reason: 'no image in summary' });
        continue;
      }
      const filename = await download(img, path.join(PICS, c.id));
      manifest[c.id] = filename;
      console.log(`↓ ${c.id} ← ${title} (${filename})`);
    } catch (err) {
      misses.push({ id: c.id, reason: err.message });
    }
    // Be polite to Wikipedia.
    await new Promise(r => setTimeout(r, 800));
  }

  writeManifest(manifest);
  console.log(`\nWrote ${MANIFEST}`);
  console.log(`Photos: ${Object.keys(manifest).length}/${candidates.length}`);
  if (misses.length) {
    console.log('\nMisses:');
    for (const m of misses) console.log(`  - ${m.id}: ${m.reason}`);
  }
}

main().catch(err => { console.error(err); process.exit(1); });
