#!/usr/bin/env node
// Smart-matchup engine simulator.
//
// Spins up the same Glicko-2 + matchup-picker logic as app.js, but in
// node, and runs N synthetic ballots with random "voter" preferences.
// Reports: median votes-to-stop in Tier 1, distribution of total Tier-1
// vote counts, and the fraction of post-R2 matchups generated by the
// "close-rated" branch.
//
// Usage: node scripts/sim_engine.js [N=1000]

const fs = require('fs');
const path = require('path');
const vm = require('vm');
const G = require('../lib/glicko2.js');

// Load candidates.js into a stub window.
const src = fs.readFileSync(path.join(__dirname, '..', 'candidates.js'), 'utf8');
const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(src, ctx);
const POOL = [...(ctx.window.CANDIDATES || []), ...(ctx.window.EXTENDED_CANDIDATES || [])];
const TIER1 = POOL.filter(c => c.tier === 1);
const R2_RIVAL = ctx.window.R2_RIVAL;
const byId = Object.fromEntries(POOL.map(c => [c.id, c]));

const RATING_INIT = 1500, RD_INIT = 350, SIGMA_INIT = 0.06;
const CI90 = 1.645;
const ADAPTIVE_P_CLOSE = 0.7;
const T1 = { floor: 10, cap: 18, topN: 5 };

function newRun() {
  const ratings = Object.fromEntries(TIER1.map(c => [c.id, RATING_INIT]));
  const rd      = Object.fromEntries(TIER1.map(c => [c.id, RD_INIT]));
  const sigma   = Object.fromEntries(TIER1.map(c => [c.id, SIGMA_INIT]));
  const appearances = Object.fromEntries(TIER1.map(c => [c.id, 0]));
  // Synthetic voter preference: each candidate gets a true "score" the voter
  // would assign. Pick winner probabilistically from a soft-max of these.
  const truth = Object.fromEntries(TIER1.map(c => [c.id, Math.random()]));
  return { ratings, rd, sigma, appearances, truth, history: [], close: 0, adaptive: 0 };
}

function allowedPairs(state) {
  const pool = TIER1;
  const minN = Math.min(...pool.map(c => state.appearances[c.id]));
  if (minN === 0) {
    const unseen = pool.filter(c => state.appearances[c.id] === 0);
    const pairs = [];
    if (unseen.length >= 2) {
      for (let i = 0; i < unseen.length; i++)
        for (let j = i + 1; j < unseen.length; j++) pairs.push([unseen[i], unseen[j]]);
      return pairs;
    }
    const u = unseen[0];
    const others = pool.filter(c => c.id !== u.id);
    const sameParty = others.filter(c => c.party === u.party);
    for (const o of (sameParty.length ? sameParty : others)) pairs.push([u, o]);
    return pairs;
  }
  const pairs = [];
  for (let i = 0; i < pool.length; i++)
    for (let j = i + 1; j < pool.length; j++) pairs.push([pool[i], pool[j]]);
  return pairs;
}

function pickClosest(state, pairs) {
  let best = pairs[0]; let bestD = Infinity;
  for (const p of pairs) {
    const d = Math.abs(state.ratings[p[0].id] - state.ratings[p[1].id]);
    if (d < bestD) { bestD = d; best = p; }
  }
  return best;
}

function pickNext(state) {
  if (state.history.length === 0) return [byId.vance, byId.newsom];
  if (state.history.length === 1) {
    const winId = state.history[0].pickedId;
    const rivalId = R2_RIVAL[winId];
    if (rivalId && byId[rivalId] && byId[rivalId].tier === 1) {
      return [byId[winId], byId[rivalId]];
    }
  }
  const pairs = allowedPairs(state);
  const close = Math.random() < ADAPTIVE_P_CLOSE;
  state.adaptive += 1;
  if (close) { state.close += 1; return pickClosest(state, pairs); }
  return pairs[Math.floor(Math.random() * pairs.length)];
}

function applyUpdate(state, pickedId, lostId) {
  const Pp = { rating: state.ratings[pickedId], rd: state.rd[pickedId], sigma: state.sigma[pickedId] };
  const Pl = { rating: state.ratings[lostId],   rd: state.rd[lostId],   sigma: state.sigma[lostId] };
  const nP = G.rateOne(Pp, [{ rating: Pl.rating, rd: Pl.rd }], [1]);
  const nL = G.rateOne(Pl, [{ rating: Pp.rating, rd: Pp.rd }], [0]);
  state.ratings[pickedId] = nP.rating; state.rd[pickedId] = nP.rd; state.sigma[pickedId] = nP.sigma;
  state.ratings[lostId]   = nL.rating; state.rd[lostId]   = nL.rd; state.sigma[lostId]   = nL.sigma;
  state.appearances[pickedId] += 1;
  state.appearances[lostId]   += 1;
}

function shouldStop(state) {
  const n = state.history.length;
  if (n >= T1.cap) return true;
  if (n < T1.floor) return false;
  const sorted = TIER1.slice().sort((a, b) => state.ratings[b.id] - state.ratings[a.id]);
  for (let i = 0; i < T1.topN - 1; i++) {
    const hiNext = state.ratings[sorted[i + 1].id] + CI90 * state.rd[sorted[i + 1].id];
    const loThis = state.ratings[sorted[i].id]     - CI90 * state.rd[sorted[i].id];
    if (loThis <= hiNext) return false;
  }
  return true;
}

function simulateOne() {
  const s = newRun();
  while (!shouldStop(s)) {
    const [a, b] = pickNext(s);
    // Voter picks via soft probability based on truth difference.
    const dt = s.truth[a.id] - s.truth[b.id];
    const pA = 1 / (1 + Math.exp(-6 * dt));
    const pickA = Math.random() < pA;
    const pickedId = pickA ? a.id : b.id;
    const lostId   = pickA ? b.id : a.id;
    applyUpdate(s, pickedId, lostId);
    s.history.push({ aId: a.id, bId: b.id, pickedId, lostId });
  }
  return s;
}

const N = parseInt(process.argv[2] || '1000', 10);
const runs = [];
for (let i = 0; i < N; i++) runs.push(simulateOne());

const votes = runs.map(r => r.history.length).sort((a, b) => a - b);
const median = votes[Math.floor(votes.length / 2)];
const p10 = votes[Math.floor(votes.length * 0.1)];
const p90 = votes[Math.floor(votes.length * 0.9)];
const meanCloseFraction = runs.reduce((acc, r) => acc + (r.adaptive ? r.close / r.adaptive : 0), 0) / N;
// Coverage check: % of runs where every Tier-1 candidate appeared ≥ once.
const fullCov = runs.filter(r => Object.values(r.appearances).every(v => v >= 1)).length;

console.log(`\nSimulated ${N} Tier-1 ballots`);
console.log(`──────────────────────────────`);
console.log(`Votes per ballot:  p10=${p10}  median=${median}  p90=${p90}  cap=${T1.cap}`);
console.log(`Capped at ${T1.cap}: ${(runs.filter(r => r.history.length === T1.cap).length / N * 100).toFixed(1)}%`);
console.log(`Stopped early:     ${(runs.filter(r => r.history.length < T1.cap).length / N * 100).toFixed(1)}%`);
console.log(`Full coverage:     ${(fullCov / N * 100).toFixed(1)}%  (target: 100% — every Tier-1 cand seen ≥ 1×)`);
console.log(`Adaptive close-rated fraction: ${(meanCloseFraction * 100).toFixed(1)}%  (target ≈ 70%)`);
